### ISSUE TITLE
multiple connections lost

### ISSUE THREAD

**Issue by pdobrien3** [pyalarmdotcom/alarmdotcom#134]
wonder if anyone is seeing these on the regular or if it is just an edge case related to my system?

![image0](https://user-images.githubusercontent.com/28842285/174798402-df507bc7-27ea-46ff-956c-e379b6882948.jpeg)

**Comment by Valdorama** [comment]
I see those in my logs but they're pretty infrequent - by which I mean maybe once per day, and don't really seem to affect anything.

**Comment by pdobrien3** [comment]
Ok, for some reason they seem to be popping up more frequently for me lately. What do you have your update interval set at?  I wonder if that is generating more issues?

**Comment by Valdorama** [comment]
120 seconds

**Comment by elahd** [comment]
Is this still an issue?

**Comment by pdobrien3** [comment]
It’s still happening. A couple times a day. Not sure if it is an issue or just the way things are. I have my update interval at 15 secs though I think.

**Comment by pdobrien3** [comment]
How do I check if the login I am using has full access to the devices? I would imagine so. 

I do not have a skybell and I am on 2022.7.3

**Comment by pdobrien3** [comment]
could it be related to this
![image1](https://user-images.githubusercontent.com/28842285/178459014-e99135f0-f0c6-460a-a36e-a9bfdca79fbf.jpeg)
?

**Comment by pdobrien3** [comment]
i disabled that entity and it didn't help.  is there a debug string i can use to see what is going on?

**Comment by elahd** [comment]
> How do I check if the login I am using has full access to the devices? I would imagine so.

1. Log in to Alarm.com with an account other than the account you use to log into Home Assistant.
2. Go to Users > Manage Logins. Click on the account you use with Home Assistant.

You'll see this:

![image](https://user-images.githubusercontent.com/466460/178761829-ccd354c5-87de-4340-b5c6-584f0eb19424.png)

The account needs to be _either_ "Full Control" or "Custom" with "Remote Arming" enabled for the Alarm Control Panel to work properly.

> could it be related to this

That may be a symptom and not a cause.

> is there a debug string i can use to see what is going on?

Add the following to your Home Assistant configuration.yaml, then reboot:

```yaml
logger:
  default: warn
  logs:
    custom_components.alarmdotcom: debug
    pyalarmdotcomajax: debug
```

I'm thinking that this could also be a hardware issue.

- What device is HA running on? I got errors like these for other integrations on a Pi 3 that resolved when upgrading to a Pi 4.
- If it's a Pi with an SD card, what speed is the card?
- Are you connected via WiFi or Ethernet?
- If your internet connection stable?

You could also try increasing your refresh interval to 60 seconds at least temporarily to see if the issue resolves.

**Comment by pdobrien3** [comment]
Ok, I created a new account without 2F identification and enabled the debug logs.  I am running HAss container in a VM on a NUC so I don’t think that is a factor.  I am connected via a wired connection and pretty sure I have stable internet.  If I recall correctly, these errors popped up when the integration went to a UI config. 

Will see what happens today.

**Comment by pdobrien3** [comment]
so i went all day without a single error.  not sure if that means 2f is an issue or my network is an issue.  i had the scan rate set at the default 30 seconds.  going to bump it back tom15 and see what happens

**Comment by elahd** [comment]
That's strange. Two factor shouldn't be an issue after the initial log in. During log in, the integration uses your OTP to generate a 2FA cookie that never expires. From then on, there isn't really any difference between using 2FA and not.

**Comment by pdobrien3** [comment]
so, things went a little haywire last night without 2FA enabled, easily fixed this am, but the errors are back.  Here is what is in the logs:

```
Logger: pyalarmdotcomajax
Source: /usr/local/lib/python3.10/site-packages/pyalarmdotcomajax/__init__.py:939
First occurred: 9:51:34 AM (1 occurrences)
Last logged: 9:51:34 AM

Error fetching data from Alarm.com.
```
```
2022-07-15 09:51:34 DEBUG (MainThread) [pyalarmdotcomajax] Got trouble conditions:
{'errors': [{'status': '403', 'detail': 'NotAllowed', 'code': 403}]}
2022-07-15 09:51:34 DEBUG (MainThread) [pyalarmdotcomajax] _async_get_items_and_subordinates(): Failed to get data for device type DeviceType.CAMERA. Response: [{'status': '403', 'detail': 'NotAllowed', 'code': 403}]. Errors: {'errors': [{'status': '403', 'detail': 'NotAllowed', 'code': 403}]}.
2022-07-15 09:51:34 ERROR (MainThread) [pyalarmdotcomajax] Error fetching data from Alarm.com.
2022-07-15 09:51:34 ERROR (MainThread) [pyalarmdotcomajax] Trying to refresh auth tokens by logging in again.
2022-07-15 09:51:34 DEBUG (MainThread) [pyalarmdotcomajax] Attempting to log in to Alarm.com
2022-07-15 09:51:34 DEBUG (MainThread) [pyalarmdotcomajax] Response status from Alarm.com: 200
```

**Comment by pdobrien3** [comment]
```
2022-07-15 15:33:33 ERROR (MainThread) [custom_components.alarmdotcom.alarmhub] Unexpected error fetching Surety:xxxxxxxxx@gmail.com data: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pyalarmdotcomajax/__init__.py", line 847, in _async_get_trouble_conditions
    json_rsp = await (resp.json())
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=us-ascii', url=URL('https://www.alarm.com/web/api/troubleConditions/troubleConditions?forceRefresh=false')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/alarmdotcom/alarmhub.py", line 209, in async_update
    await self.system.async_update()
  File "/usr/local/lib/python3.10/site-packages/pyalarmdotcomajax/__init__.py", line 333, in async_update
    await self._async_get_trouble_conditions()
  File "/usr/local/lib/python3.10/site-packages/pyalarmdotcomajax/__init__.py", line 874, in _async_get_trouble_conditions
    raise DataFetchFailed from err
pyalarmdotcomajax.errors.DataFetchFailed
```

**Comment by elahd** [comment]
Can you update to v0.2.12-beta.1? This will show more detail in the last error you posted.

**Comment by pdobrien3** [comment]
Done. Will let you know. I suppose I should have mentioned it again to make sure but I don’t have any cameras.

**Comment by pdobrien3** [comment]
getting pretty much the same thing
```
2022-07-22 21:51:03 DEBUG (MainThread) [custom_components.alarmdotcom.alarmhub] custom_components.alarmdotcom.alarmhub: Requesting update from Alarm.com.
2022-07-22 21:51:03 DEBUG (MainThread) [pyalarmdotcomajax] Calling update on Alarm.com
2022-07-22 21:52:04 DEBUG (MainThread) [pyalarmdotcomajax] Got trouble conditions:
{'errors': [{'status': '403', 'detail': 'NotAllowed', 'code': 403}]}
2022-07-22 21:52:04 DEBUG (MainThread) [pyalarmdotcomajax] _async_get_items_and_subordinates(): Failed to get data for device type DeviceType.CAMERA. Response: [{'status': '403', 'detail': 'NotAllowed', 'code': 403}]. Errors: {'errors': [{'status': '403', 'detail': 'NotAllowed', 'code': 403}]}.
2022-07-22 21:52:04 ERROR (MainThread) [pyalarmdotcomajax] Error fetching data from Alarm.com.
2022-07-22 21:52:04 ERROR (MainThread) [pyalarmdotcomajax] Trying to refresh auth tokens by logging in again.
2022-07-22 21:52:04 DEBUG (MainThread) [pyalarmdotcomajax] Attempting to log in to Alarm.com
2022-07-22 21:52:04 DEBUG (MainThread) [pyalarmdotcomajax] Response status from Alarm.com: 200
```

**Comment by elahd** [comment]
Which plan do you have?
https://suretyhome.com/plans/. Just alarm or alarm with automation / smart
devices?

**Comment by pdobrien3** [comment]
I have the home plan without any add-ons

**Comment by elahd** [comment]
That makes sense. The integration assumes that 403 / not authorized error
means that the user has been logged out. (Weird edge case.) With your plan,
403 means that the service is not available in the plan.

I’ll fix this in a bit.

**Comment by elahd** [comment]
Try v0.2.12-beta.2

**Comment by pdobrien3** [comment]
Lots of new errors.  The alarm isnt working now.  Bumping back to v0.2.12-beta.1

```
custom_components.alarmdotcom.alarmhub: Update failed: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=us-ascii', url=URL('https://www.alarm.com/web/api/devices/sensors/')

Error requesting xxxxx:xxxxxxx@gmail.com data: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=us-ascii', url=URL('https://www.alarm.com/web/api/devices/sensors/')

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 447, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 680, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1713, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1750, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 680, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 930, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 717, in _handle_entity_call
    await result
  File "/config/custom_components/alarmdotcom/alarm_control_panel.py", line 200, in async_alarm_arm_away
    await self._device.async_arm_away(
AttributeError: 'NoneType' object has no attribute 'async_arm_away'

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 151, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 110, in async_update_listeners
    update_callback()
  File "/config/custom_components/alarmdotcom/base_device.py", line 160, in _handle_coordinator_update
    super()._handle_coordinator_update()
  File "/config/custom_components/alarmdotcom/base_device.py", line 97, in _handle_coordinator_update
    "raw_state_text": self._device.raw_state_text,
AttributeError: 'NoneType' object has no attribute 'raw_state_text'
```

**Comment by elahd** [comment]
Really weird.

If you're comfortable with the command line...

1. Install [Python >= 3.9](https://www.python.org/downloads/).
2. Open a command prompt (Windows) or terminal (Mac/Linux).
3. Install pip via `python -m ensurepip --upgrade`.
4. Install [pyalarmdotcomajax](https://github.com/pyalarmdotcom/pyalarmdotcomajax) via pip: `pip install pyalarmdotcomajax`
5. Get your device data using `adc -v -u "USERNAME" -p "PASSWORD" get -x`, substituting your own username and password. You'll be prompted for an OTP if you have two factor authentication enabled.
6. Post the output here.

Don't forget to remove any information that you consider sensitive (your address, name, rooms named after family members - e.g.: "Elahd's Bedroom", etc.). Some people also scrub sensor IDs, but I'm not sure of whether that's actually sensitive. Please keep sensor names as intact as possible (e.g.: Elahd's Bedoom -> Bedroom) instead of fully deleting them. The context is helpful.

**Comment by pdobrien3** [comment]
I will work on getting it. All my devices tied to adc are sensors though. Door/window sensors, smoke detectors, ect.  The error I keep seeing is for a camera.

**Comment by pdobrien3** [comment]
[sensors_formatted_sanitized.txt](https://github.com/pyalarmdotcom/alarmdotcom/files/9188968/sensors_formatted_sanitized.txt)

**Comment by elahd** [comment]
Are there any other device types? I don't see your partition here -- that's how Alarm.com represents your alarm control panel.

**Comment by pdobrien3** [comment]
====[GARAGE_DOORS]====

{"data": [], "included": [], "meta": {"transformer_version": "1.1"}}

====[PARTITIONS]====

{"data": [{"id": "", "type": "devices/partition", "attributes": {"partitionId": 1, "state": 2, "desiredState": 2, "extendedArmingOptions": {"Disarmed": [], "ArmedStay": [1], "ArmedAway": [1], "ArmedNight": []}, "invalidExtendedArmingOptions": {"Disarmed": [], "ArmedStay": [], "ArmedAway": [], "ArmedNight": []}, "needsClearIssuesPrompt": false, "canEnableAlexa": false, "isAlexaEnabled": false, "canAccessPanelWifi": false, "canScanForWifi": false, "sensorNamingFormat": 3, "managedDeviceType": 9, "canBeRenamed": true, "canAccessWebSettings": true, "canAccessAppSettings": true, "webSettings": 1002, "hasState": true, "canBeDeleted": false, "canAccessTroubleshootingWizard": false, "troubleshootingWizard": null, "macAddress": "", "manufacturer": "", "isOAuth": false, "isZWave": false, "supportsCommandClassBasic": false, "isMalfunctioning": false, "canBeSaved": true, "canChangeDescription": true, "description": "System", "deviceModelId": , "canConfirmStateChange": true, "canReceiveCommands": true, "remoteCommandsEnabled": true, "hasPermissionToChangeState": true, "deviceIcon": {"icon": 185}, "batteryLevelNull": null, "lowBattery": false, "criticalBattery": false, "canBeLinkedToVideoDevice": false, "videoDeviceLinkDeviceIds": []}, "relationships": {"sensors": {"data": [{"id": "", "type": "devices/sensor"}, {"id": "", "type": "devices/sensor"}, {"id": "", "type": "devices/sensor"}, {"id": "", "type": "devices/sensor"}, {"id": "", "type": "devices/sensor"}, {"id": "", "type": "devices/sensor"}, {"id": "", "type": "devices/sensor"}, {"id": "", "type": "devices/sensor"}, {"id": "", "type": "devices/sensor"}, {"id": "", "type": "devices/sensor"}, {"id": "", "type": "devices/sensor"}, {"id": "", "type": "devices/sensor"}, {"id": "", "type": "devices/sensor"}, {"id": "", "type": "devices/sensor"}, {"id": "", "type": "devices/sensor"}, {"id": "", "type": "devices/sensor"}, {"id": "", "type": "devices/sensor"}], "meta": {"count": "17"}}, "system": {"data": {"id": "", "type": "systems/system"}}, "stateInfo": {"data": {"id": "", "type": "devices/state-info"}}}}], "included": [], "meta": {"transformer_version": "1.1"}}

**Comment by pdobrien3** [comment]
is that firet line possibly new info that is helpful?

```
2022-07-27 17:12:55.805 INFO (MainThread) [homeassistant.components.websocket_api.http.connection] [140494887806976] Connection closed by client
2022-07-27 17:13:04.666 DEBUG (MainThread) [pyalarmdotcomajax] Got trouble conditions:
{'errors': [{'status': '403', 'detail': 'NotAllowed', 'code': 403}]}
2022-07-27 17:13:04.854 DEBUG (MainThread) [pyalarmdotcomajax] _async_get_items_and_subordinates(): Failed to get data for device type DeviceType.CAMERA. Response: [{'status': '403', 'detail': 'NotAllowed', 'code': 403}]. Errors: {'errors': [{'status': '403', 'detail': 'NotAllowed', 'code': 403}]}.
2022-07-27 17:13:04.854 ERROR (MainThread) [pyalarmdotcomajax] Error fetching data from Alarm.com.
2022-07-27 17:13:04.856 ERROR (MainThread) [pyalarmdotcomajax] Trying to refresh auth tokens by logging in again.
2022-07-27 17:13:04.857 DEBUG (MainThread) [pyalarmdotcomajax] Attempting to log in to Alarm.com
2022-07-27 17:13:05.119 DEBUG (MainThread) [pyalarmdotcomajax] Response status from Alarm.com: 200
```

**Comment by pdobrien3** [comment]
latest error on 0.2.12 and i can control my alarm panel:

```
Logger: homeassistant
Source: custom_components/alarmdotcom/base_device.py:97
Integration: Alarm.com ([documentation](https://www.github.com/uvjustin/alarmdotcom), [issues](https://www.github.com/uvjustin/alarmdotcom/issues))
First occurred: 2:35:21 PM (213 occurrences)
Last logged: 3:28:22 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 151, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 110, in async_update_listeners
    update_callback()
  File "/config/custom_components/alarmdotcom/base_device.py", line 160, in _handle_coordinator_update
    super()._handle_coordinator_update()
  File "/config/custom_components/alarmdotcom/base_device.py", line 97, in _handle_coordinator_update
    "raw_state_text": self._device.raw_state_text,
AttributeError: 'NoneType' object has no attribute 'raw_state_text'
```

**Comment by pdobrien3** [comment]
```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/alarmdotcom/alarm_control_panel.py:180
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 3:27:54 PM (1 occurrences)
Last logged: 3:27:54 PM

[139836591240816] 'NoneType' object has no attribute 'async_arm_stay'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1713, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1750, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 676, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 930, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 713, in _handle_entity_call
    await result
  File "/config/custom_components/alarmdotcom/alarm_control_panel.py", line 180, in async_alarm_arm_home
    await self._device.async_arm_stay(
AttributeError: 'NoneType' object has no attribute 'async_arm_stay'
```

**Comment by pdobrien3** [comment]
now that i think about it though, i upgraded shortly after 0.2.12 came out and it was working fine until today

**Comment by pdobrien3** [comment]
ok, i payed attention this time.  looks like this error happens:

```
Logger: pyalarmdotcomajax
Source: /usr/local/lib/python3.10/site-packages/pyalarmdotcomajax/__init__.py:857
First occurred: August 6, 2022 at 10:46:02 PM (1 occurrences)
Last logged: August 6, 2022 at 10:46:02 PM

Connection error while fetching trouble conditions.
```
and then the `AttributeError: 'NoneType' object has no attribute 'raw_state_text'` starts happening everytime it tried to get a state and you cant control the panel from hass.  if you reload the integration, the errors stop and everything works again.

**Comment by elahd** [comment]
When that happens, can you press the debug button on the alarm control panel in Home Assistant and paste the debug logs here?

First:

![image](https://user-images.githubusercontent.com/466460/184538810-dbc8324f-d789-406f-afe3-c0a71ccf3580.png)

Then check HA's logs for a debug entry:

![image](https://user-images.githubusercontent.com/466460/184538844-3f13e880-ede0-4c65-96fb-52bfc51103ff.png)

![image](https://user-images.githubusercontent.com/466460/184538873-be612f68-3650-456a-8146-8d05daae4911.png)

**Comment by pdobrien3** [comment]
When it happens? Or after it happens? It happens so quick I don’t think I will be able to do it when it happens.

**Comment by pdobrien3** [comment]
This error originated from a custom integration.

```
Logger: custom_components.alarmdotcom
Source: custom_components/alarmdotcom/__init__.py:133
Integration: Alarm.com (documentation, issues)
First occurred: 10:39:56 AM (1 occurrences)
Last logged: 10:39:56 AM

ALARM.COM DEBUG DATA FOR SYSTEM: {"partitionId": 1, "state": 1, "desiredState": 1, "extendedArmingOptions": {"Disarmed": [], "ArmedStay": [2, 1], "ArmedAway": [2, 1], "ArmedNight": []}, "invalidExtendedArmingOptions": {"Disarmed": [], "ArmedStay": [], "ArmedAway": [], "ArmedNight": []}, "needsClearIssuesPrompt": false, "canEnableAlexa": false, "isAlexaEnabled": false, "canAccessPanelWifi": false, "canScanForWifi": false, "canBypassSensorWhenArmed": false, "sensorNamingFormat": 3, "managedDeviceType": 10, "canBeRenamed": true, "canAccessWebSettings": true, "canAccessAppSettings": true, "webSettings": 1002, "hasState": true, "canBeDeleted": false, "canAccessTroubleshootingWizard": false, "troubleshootingWizard": null, "canBeAssociatedToVideoDevice": false, "associatedCameraDeviceIds": {}, "macAddress": "", "manufacturer": "", "isOAuth": false, "isZWave": false, "supportsCommandClassBasic": false, "isMalfunctioning": false, "canBeSaved": true, "canChangeDescription": true, "description": "System", "deviceModelId": 6791, "canConfirmStateChange": true, "canReceiveCommands": true, "remoteCommandsEnabled": true, "hasPermissionToChangeState": true, "deviceIcon": {"icon": 184}, "batteryLevelNull": null, "lowBattery": false, "criticalBattery": false}
```

**Comment by pdobrien3** [comment]
This thread has been through so many versions, and quite honestly, the latest updates have changed things drastically.  I am closing this and will reevaluate the error messages and if needed, open a new issue.
