### ISSUE TITLE
[BUG] - AttributeError: 'NoneType' Log Message Spam

### ISSUE THREAD

**Issue by Lurick73** [pyalarmdotcom/alarmdotcom#157]
Noticed the following log messages appearing in the integration as of late in the home-assistant.log file every minute following a reload of the HomeAssistant service which continue until I manually restart HA again or reload the integration. The below message seems to precede this issue:
2022-08-07 00:59:03.090 ERROR (MainThread) [custom_components.alarmdotcom.alarmhub] custom_components.alarmdotcom.alarmhub: Update failed: [Errno 104] Connection reset by peer
2022-08-07 00:59:03.092 ERROR (MainThread) [custom_components.alarmdotcom.alarmhub] Error requesting GeoArm Security®:[email] data: [Errno 104] Connection reset by peer
2022-08-07 00:59:33.182 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/update_coordinator.py", line 151, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.async_update_listeners()
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/update_coordinator.py", line 110, in async_update_listeners
    update_callback()
  File "/home/homeassistant/.homeassistant/custom_components/alarmdotcom/base_device.py", line 160, in _handle_coordinator_update
    super()._handle_coordinator_update()
  File "/home/homeassistant/.homeassistant/custom_components/alarmdotcom/base_device.py", line 97, in _handle_coordinator_update
    "raw_state_text": self._device.raw_state_text,
AttributeError: 'NoneType' object has no attribute 'raw_state_text'

Log message from HA GUI:
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/alarmdotcom/base_device.py:97
Integration: Alarm.com (documentation, issues)
First occurred: 12:59:33 AM (978 occurrences)
Last logged: 9:09:08 AM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/update_coordinator.py", line 151, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.async_update_listeners()
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/update_coordinator.py", line 110, in async_update_listeners
    update_callback()
  File "/home/homeassistant/.homeassistant/custom_components/alarmdotcom/base_device.py", line 160, in _handle_coordinator_update
    super()._handle_coordinator_update()
  File "/home/homeassistant/.homeassistant/custom_components/alarmdotcom/base_device.py", line 97, in _handle_coordinator_update
    "raw_state_text": self._device.raw_state_text,
AttributeError: 'NoneType' object has no attribute 'raw_state_text'

**Comment by Anto79-ops** [comment]
hi, can confirm the same message message in my logs also

using:

alarmdotcom: v0.2.12 
Home Assistant 2022.8.2
Supervisor 2022.08.2
Operating System 8.4
Frontend 20220802.0 - latest


```
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/alarmdotcom/base_device.py:97
Integration: Alarm.com (documentation, issues)
First occurred: 9:30:36 PM (30 occurrences)
Last logged: 10:00:05 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 151, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 110, in async_update_listeners
    update_callback()
  File "/config/custom_components/alarmdotcom/base_device.py", line 160, in _handle_coordinator_update
    super()._handle_coordinator_update()
  File "/config/custom_components/alarmdotcom/base_device.py", line 97, in _handle_coordinator_update
    "raw_state_text": self._device.raw_state_text,
AttributeError: 'NoneType' object has no attribute 'raw_state_text'

```

thanks!

**Comment by Anto79-ops** [comment]
just an update, this is flooding my logs, its over 1000 occurrences since last night.

if there is a quick fix, I'd happy to try it.
