### ISSUE TITLE
Instant function and access to scenes?

### ISSUE THREAD

**Issue by thomasshawn** [pyalarmdotcom/alarmdotcom#199]
Using ADC with DSC panels. When at home we use *9 function to remove entry delay at night.  I have a "scene" setup on my web portal/app that locks down both partitions with a night mode which removes any delay on opening. 

On my install the only button I can get to work on the integration is ARM HOME. If I use away, or night, or vacation I get unable to call service error.

I've tried to read everything I can here and on home assistant forum but can't find anything. Saw a reference to using example yaml file but I dont see one and also dont see any changes to my yaml file with this integration.

Looking for a way to enable this instant function. potentially to enable the other away and night buttons as well. 
on my web interface I have arm stay and arm home. from that I with several "scenes" that are tweaked off of those 2 options that allow the instant function. also allows arming 1 partion over another etc. is there a way to call those "scenes" ? 

that might be an easier way to get to the instant function than coding it specifically.

**Comment by elahd** [comment]
> On my install the only button I can get to work on the integration is ARM HOME.

This should be fixed in [v2.0.21](https://github.com/pyalarmdotcom/alarmdotcom/releases/tag/v2.0.21). Can you try again after updating?

>  potentially to enable the other away and night buttons as well.

Arm Night needs to be enabled manually by editing the frontend alarm control panel card. The button won't appear on its own, even when the underlying alarm control panel supports it.

![image](https://user-images.githubusercontent.com/466460/211637075-83c3902c-a3cd-4074-adf7-376db4ba01a4.png)

> Looking for a way to enable this instant function.

You should be able to do this by changing the config for the Alarm.com integration. In HA, go to Settings > Integrations and hit the Configure button for the Alarm.com integration. This calls a General Settings popup. Click Next to get to this screen:

![image](https://user-images.githubusercontent.com/466460/211637584-7ddf6845-131e-462e-a0ca-83a3855303f2.png)

Turning off "Arming Delay" for Arm Home and Arm Night should get you what you want.

Can you try this and report back?

**Comment by thomasshawn** [comment]
On current version, same issue when I choose night option from the card edit funtion I get failed to call service. I have tried to enable the night function as you described before I emailed you but I tried again.
![ymail-tmp-2127092216148418775](https://user-images.githubusercontent.com/118871294/211708983-217496d7-3500-4ca4-8095-0f2492cd848d.jpg)

As for the delays here's everything I have and nothing is working. Turning off the arming delay doesn't change anything unfortunately 

![ymail-tmp-8060721354657980336](https://user-images.githubusercontent.com/118871294/211709197-68617cb7-b699-4d88-8af7-2bb4510b5e01.jpg)

![ymail-tmp-2303028137620401906](https://user-images.githubusercontent.com/118871294/211709820-a0cbc2d7-708f-487f-9ff4-05487693e92a.jpg)

**Comment by elahd** [comment]
Thanks for the detail. Would you mind setting up debugging and capturing the server response? You can do that with [these instructions](https://github.com/pyalarmdotcom/alarmdotcom/wiki/How-to-Test-&-Debug#enable-code-debugging). Once in debug mode, you should be able to find the entries by searching the log for `nightArming` or `night_arming`.

Thanks!

**Comment by thomasshawn** [comment]
was out of town and wanted to do this locally in case it caused issues.

to be clear I'm not asking to turn on/off the **arming delay**  as you mentioned above in the night mode I'm asking to turn on the **no-entry delay** as shown in this screenshot.


![thumbnail](https://user-images.githubusercontent.com/118871294/212546290-be8f75b2-311d-41df-9b0f-6cd76116d843.jpeg)


 I just want to be sure we're trying to achieve the same goal.

NIGHT mode doesn't work for me and here is the log for it.

not sure if this is what you are wanting but this is what I got back

this is an Arm_NIGHT call 
**basically shows a failed with HTTP code 422**

 not sure what to post here from within the log don't necessarily wan to expose  keys/unique IDs  that appear to show in the log file

_2023-01-15 07:49:28.136 DEBUG (MainThread) [pyalarmdotcomajax.devices.partition] Calling arm night.
2023-01-15 07:49:28.137 DEBUG (MainThread) [pyalarmdotcomajax] Sending Command.ARM_STAY to Alarm.com.
2023-01-15 07:49:28.146 DEBUG (MainThread) [pyalarmdotcomajax] Url https://www.alarm.com/web/api/devices/partitions/XXXXXXX/armStay
2023-01-15 07:49:28.428 DEBUG (MainThread) [pyalarmdotcomajax] Response from Alarm.com 422
2023-01-15 07:49:28.429 ERROR (MainThread) [pyalarmdotcomajax] armStay failed with HTTP code 422
2023-01-15 07:49:28.437 ERROR (MainThread) [pyalarmdotcomajax] URL: https://www.alarm.com/web/api/devices/partitions/XXXXXXX/armStay
JSON: {'forceBypass': False, 'noEntryDelay': True, 'silentArming': False, 'nightArming': True, 'statePollOnly': False}
Headers: {'Accept': 'application/vnd.api+json', 'ajaxrequestuniquekey': 'XXXXXXXXXXXXXXXXXX'}
2023-01-15 07:49:28.441 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [XXXXXXXXXXX]
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1755, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1792, in _execute_service
await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
await service.entity_service_call(
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
future.result() # pop exception if have
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 958, in async_request_call
await coro
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
await result
File "/config/custom_components/alarmdotcom/alarm_control_panel.py", line 161, in async_alarm_arm_night
await self._device.async_arm_night(
File "/usr/local/lib/python3.10/site-packages/pyalarmdotcomajax/devices/partition.py", line 147, in async_arm_night
await self._async_arm(
File "/usr/local/lib/python3.10/site-packages/pyalarmdotcomajax/devices/partition.py", line 94, in _async_arm
await self._send_action_callback(
File "/usr/local/lib/python3.10/site-packages/pyalarmdotcomajax/__init__.py", line 440, in async_send_command
raise ConnectionError
ConnectionError
2023-01-15 07:49:40.492 DEBUG (MainThread) [pyalarmdotcomajax.devices.partition] Calling arm night.
2023-01-15 07:49:40.492 DEBUG (MainThread) [pyalarmdotcomajax] Sending Command.ARM_STAY to Alarm.com.
2023-01-15 07:49:40.493 DEBUG (MainThread) [pyalarmdotcomajax] Url https://www.alarm.com/web/api/devices/partitions/XXXXXXX-XXX/armStay
2023-01-15 07:49:40.566 DEBUG (MainThread) [pyalarmdotcomajax] Response from Alarm.com 422
2023-01-15 07:49:40.567 ERROR (MainThread) [pyalarmdotcomajax] armStay failed with HTTP code 422
2023-01-15 07:49:40.571 ERROR (MainThread) [pyalarmdotcomajax] URL: https://www.alarm.com/web/api/devices/partitions/XXXXXXX-XXX/armStay
JSON: {'forceBypass': False, 'noEntryDelay': True, 'silentArming': False, 'nightArming': True, 'statePollOnly': False}
Headers: {'Accept': 'application/vnd.api+json', 'ajaxrequestuniquekey': 'XXXXXXXXXX'}
2023-01-15 07:49:40.573 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [XXXXXXXX]
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1755, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1792, in _execute_service
await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
await service.entity_service_call(
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
future.result() # pop exception if have
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 958, in async_request_call
await coro
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
await result
File "/config/custom_components/alarmdotcom/alarm_control_panel.py", line 161, in async_alarm_arm_night
await self._device.async_arm_night(
File "/usr/local/lib/python3.10/site-packages/pyalarmdotcomajax/devices/partition.py", line 147, in async_arm_night
await self._async_arm(
File "/usr/local/lib/python3.10/site-packages/pyalarmdotcomajax/devices/partition.py", line 94, in _async_arm
await self._send_action_callback(
File "/usr/local/lib/python3.10/site-packages/pyalarmdotcomajax/__init__.py", line 440, in async_send_command
raise ConnectionError
ConnectionError
2023-01-15 07:50:06.231 DEBUG (MainThread) [custom_components.alarmdotcom.alarmhub] custom_components.alarmdotcom.alarmhub: Requesting update from Alarm.com.
2023-01-15 07:50:06.232 DEBUG (MainThread) [pyalarmdotcomajax] Calling update on Alarm.com
2023-01-15 07:50:06.486 DEBUG (MainThread) [pyalarmdotcomajax] Trouble condition response:
{'data': [], 'included': [], 'meta': {'transformer_version': '1.1'}}
2023-01-15 07:50:06.605 DEBUG (MainThread) [pyalarmdotcomajax] _async_get_items_and_subordinates(): Failed to get data for device type DeviceType.GARAGE_DOOR. Response: [{'status': '423', 'detail': 'You do not have permissions for this device type', 'code': 423}]. Errors: {'included': [], 'errors': [{'status': '423', 'detail': 'You do not have permissions for this device type', 'code': 423}], 'meta': {'transformer_version': '1.1'}}.
2023-01-15 07:50:06.606 DEBUG (MainThread) [pyalarmdotcomajax] Error fetching data from Alarm.com. This account either doesn't have permission to DeviceType.GARAGE_DOOR, is on a plan that does not support DeviceType.GARAGE_DOOR, or is part of a system with DeviceType.GARAGE_DOOR turned off.
2023-01-15 07:50:06.661 DEBUG (MainThread) [pyalarmdotcomajax] _async_get_items_and_subordinates(): Failed to get data for device type DeviceType.GATE. Response: [{'status': '423', 'detail': 'You do not have permissions for this device type', 'code': 423}]. Errors: {'included': [], 'errors': [{'status': '423', 'detail': 'You do not have permissions for this device type', 'code': 423}], 'meta': {'transformer_version': '1.1'}}.
2023-01-15 07:50:06.661 DEBUG (MainThread) [pyalarmdotcomajax] Error fetching data from Alarm.com. This account either doesn't have permission to DeviceType.GATE, is on a plan that does not support DeviceType.GATE, or is part of a system with DeviceType.GATE turned off.
2023-01-15 07:50:06.781 DEBUG (MainThread) [pyalarmdotcomajax] _async_get_items_and_subordinates(): Failed to get data for device type DeviceType.LIGHT. Response: [{'status': '423', 'detail': 'You do not have permissions for this device type', 'code': 423}]. Errors: {'included': [], 'errors': [{'status': '423', 'detail': 'You do not have permissions for this device type', 'code': 423}], 'meta': {'transformer_version': '1.1'}}.
2023-01-15 07:50:06.781 DEBUG (MainThread) [pyalarmdotcomajax] Error fetching data from Alarm.com. This account either doesn't have permission to DeviceType.LIGHT, is on a plan that does not support DeviceType.LIGHT, or is part of a system with DeviceType.LIGHT turned off.
2023-01-15 07:50:06.835 DEBUG (MainThread) [pyalarmdotcomajax] _async_get_items_and_subordinates(): Failed to get data for device type DeviceType.LOCK. Response: [{'status': '423', 'detail': 'You do not have permissions for this device type', 'code': 423}]. Errors: {'included': [], 'errors': [{'status': '423', 'detail': 'You do not have permissions for this device type', 'code': 423}], 'meta': {'transformer_version': '1.1'}}.
2023-01-15 07:50:06.835 DEBUG (MainThread) [pyalarmdotcomajax] Error fetching data from Alarm.com. This account either doesn't have permission to DeviceType.LOCK, is on a plan that does not support DeviceType.LOCK, or is part of a system with DeviceType.LOCK turned off.
2023-01-15 07:50:06.981 DEBUG (MainThread) [pyalarmdotcomajax.devices] Initialized devices/partition HOUSE
2023-01-15 07:50:06.981 DEBUG (MainThread) [pyalarmdotcomajax.devices] Initialized devices/partition ADD-ON
2023-01-15 07:50:07.067 DEBUG (MainThread) [pyalarmdotcomajax.devices] Initialized devices/sensor 1 Front Door
2023-01-15 07:50:07.068 DEBUG (MainThread) [pyalarmdotcomajax.devices] Initialized devices/sensor 10 Garage Window & Door
2023-01-15 07:50:07.068 DEBUG (MainThread) [pyalarmdotcomajax.devices] Initialized devices/sensor 12 Upstairs Back Bed Windo
2023-01-15 07:50:07.068 DEBUG (MainThread) [pyalarmdotcomajax.devices] Initialized devices/sensor 13 Upstairs Side Bed Windo
2023-01-15 07:50:07.068 DEBUG (MainThread) [pyalarmdotcomajax.devices] Initialized devices/sensor 17 Dummy Motion
2023-01-15 07:50:07.068 DEBUG (MainThread) [pyalarmdotcomajax.devices] Initialized devices/sensor 18 Garage AC Water Bug
2023-01-15 07:50:07.069 DEBUG (MainThread) [pyalarmdotcomajax.devices] Initialized devices/sensor 19 Upstairs Attic Water #1
2023-01-15 07:50:07.069 DEBUG (MainThread) [pyalarmdotcomajax.devices] Initialized devices/sensor 2 Garage Door
2023-01-15 07:50:07.069 DEBUG (MainThread) [pyalarmdotcomajax.devices] Initialized devices/sensor 20 Upstairs Attic Water #2
2023-01-15 07:50:07.069 DEBUG (MainThread) [pyalarmdotcomajax.devices] Initialized devices/sensor 25 EXT GARAGE DOOR
2023-01-15 07:50:07.070 DEBUG (MainThread) [pyalarmdotcomajax.devices] Initialized devices/sensor 26 GARAGE WINDOWS
2023-01-15 07:50:07.070 DEBUG (MainThread) [pyalarmdotcomajax.devices] Initialized devices/sensor 27 GARAGE HEATS
2023-01-15 07:50:07.070 DEBUG (MainThread) [pyalarmdotcomajax.devices] Initialized devices/sensor 28 BEDROOM WINDOWS
2023-01-15 07:50:07.070 DEBUG (MainThread) [pyalarmdotcomajax.devices] Initialized devices/sensor 29 KITCHEN WINDOWS
2023-01-15 07:50:07.071 DEBUG (MainThread) [pyalarmdotcomajax.devices] Initialized devices/sensor 3 Master Bed Windows
2023-01-15 07:50:07.071 DEBUG (MainThread) [pyalarmdotcomajax.devices] Initialized devices/sensor 30 KITCHEN DOOR
2023-01-15 07:50:07.071 DEBUG (MainThread) [pyalarmdotcomajax.devices] Initialized devices/sensor 31 STORAGE ROOM DOOR
2023-01-15 07:50:07.071 DEBUG (MainThread) [pyalarmdotcomajax.devices] Initialized devices/sensor 32 LIVING DOOR 1
2023-01-15 07:50:07.071 DEBUG (MainThread) [pyalarmdotcomajax.devices] Initialized devices/sensor 33 LIVING ROOM GB
2023-01-15 07:50:07.072 DEBUG (MainThread) [pyalarmdotcomajax.devices] Initialized devices/sensor 34 LIVING DOOR 2
2023-01-15 07:50:07.072 DEBUG (MainThread) [pyalarmdotcomajax.devices] Initialized devices/sensor 35 HALL DOOR
2023-01-15 07:50:07.072 DEBUG (MainThread) [pyalarmdotcomajax.devices] Initialized devices/sensor 36 HALL GB
2023-01-15 07:50:07.072 DEBUG (MainThread) [pyalarmdotcomajax.devices] Initialized devices/sensor 37 GARAGE DOOR
2023-01-15 07:50:07.072 DEBUG (MainThread) [pyalarmdotcomajax.devices] Initialized devices/sensor 38 ATTIC HEATS
2023-01-15 07:50:07.073 DEBUG (MainThread) [pyalarmdotcomajax.devices] Initialized devices/sensor 39 HALL CARBON
2023-01-15 07:50:07.074 DEBUG (MainThread) [pyalarmdotcomajax.devices] Initialized devices/sensor 4 O/P Exp. 1
2023-01-15 07:50:07.076 DEBUG (MainThread) [pyalarmdotcomajax.devices] Initialized devices/sensor 4 Office Window
2023-01-15 07:50:07.076 DEBUG (MainThread) [pyalarmdotcomajax.devices] Initialized devices/sensor 40 SHOP ATTIC CARBON
2023-01-15 07:50:07.076 DEBUG (MainThread) [pyalarmdotcomajax.devices] Initialized devices/sensor 41 GARAGE ATTIC CARBON
2023-01-15 07:50:07.076 DEBUG (MainThread) [pyalarmdotcomajax.devices] Initialized devices/sensor 45 GUEST HOUSE FIRE
2023-01-15 07:50:07.077 DEBUG (MainThread) [pyalarmdotcomajax.devices] Initialized devices/sensor 49 Shop Attic Water Bug
2023-01-15 07:50:07.077 DEBUG (MainThread) [pyalarmdotcomajax.devices] Initialized devices/sensor 5 Upstairs Front Bed Wind
2023-01-15 07:50:07.077 DEBUG (MainThread) [pyalarmdotcomajax.devices] Initialized devices/sensor 50 Guest HouseWater Bug
2023-01-15 07:50:07.077 DEBUG (MainThread) [pyalarmdotcomajax.devices] Initialized devices/sensor 6 Living room Doors
2023-01-15 07:50:07.077 DEBUG (MainThread) [pyalarmdotcomajax.devices] Initialized devices/sensor 7 Breakfast Window & Doors
2023-01-15 07:50:07.077 DEBUG (MainThread) [pyalarmdotcomajax.devices] Initialized devices/sensor 8 Dining Window
2023-01-15 07:50:07.077 DEBUG (MainThread) [pyalarmdotcomajax.devices] Initialized devices/sensor 9 Utility Window
2023-01-15 07:50:07.077 DEBUG (MainThread) [pyalarmdotcomajax.devices] Initialized devices/sensor Keypad 1
2023-01-15 07:50:07.077 DEBUG (MainThread) [pyalarmdotcomajax.devices] Initialized devices/sensor Keypad 2
2023-01-15 07:50:07.077 DEBUG (MainThread) [pyalarmdotcomajax.devices] Initialized devices/sensor Keypad 3
2023-01-15 07:50:07.077 DEBUG (MainThread) [pyalarmdotcomajax.devices] Initialized devices/sensor Keypad 4
2023-01-15 07:50:07.077 DEBUG (MainThread) [pyalarmdotcomajax.devices] Initialized devices/sensor Keypad 5
2023-01-15 07:50:07.078 DEBUG (MainThread) [pyalarmdotcomajax.devices] Initialized devices/sensor PowerG Host
2023-01-15 07:50:07.078 DEBUG (MainThread) [pyalarmdotcomajax.devices] Initialized devices/sensor Zone Exp. 1
2023-01-15 07:50:07.078 DEBUG (MainThread) [pyalarmdotcomajax.devices] Initialized devices/sensor Zone Exp. 3
2023-01-15 07:50:07.078 DEBUG (MainThread) [pyalarmdotcomajax.devices] Initialized devices/sensor Zone Exp. 4
2023-01-15 07:50:07.078 DEBUG (MainThread) [pyalarmdotcomajax.devices] Initialized devices/sensor Zone Exp. 5
2023-01-15 07:50:07.187 DEBUG (MainThread) [pyalarmdotcomajax.devices] Initialized systems/system Thomas's system
2023-01-15 07:50:07.243 DEBUG (MainThread) [pyalarmdotcomajax] _async_get_items_and_subordinates(): Failed to get data for device type DeviceType.THERMOSTAT. Response: [{'status': '423', 'detail': 'You do not have permissions for this device type', 'code': 423}]. Errors: {'included': [], 'errors': [{'status': '423', 'detail': 'You do not have permissions for this device type', 'code': 423}], 'meta': {'transformer_version': '1.1'}}.
2023-01-15 07:50:07.244 DEBUG (MainThread) [pyalarmdotcomajax] Error fetching data from Alarm.com. This account either doesn't have permission to DeviceType.THERMOSTAT, is on a plan that does not support DeviceType.THERMOSTAT, or is part of a system with DeviceType.THERMOSTAT turned off.
2023-01-15 07:50:07.244 DEBUG (MainThread) [custom_components.alarmdotcom.alarmhub] Finished fetching East Texas Alarm, Inc.:shawn_thomas_99@yahoo.com data in 1.013 seconds (success: True)
2023-01-15 07:50:07.245 DEBUG (MainThread) [custom_components.alarmdotcom.binary_sensor] Processing state DeviceState.CLOSED for None
2023-01-15 07:50:07.246 DEBUG (MainThread) [custom_components.alarmdotcom.binary_sensor] Processing state DeviceState.CLOSED for None
2023-01-15 07:50:07.246 DEBUG (MainThread) [custom_components.alarmdotcom.binary_sensor] Processing state DeviceState.CLOSED for None
2023-01-15 07:50:07.247 DEBUG (MainThread) [custom_components.alarmdotcom.binary_sensor] Processing state DeviceState.CLOSED for None
2023-01-15 07:50:07.247 DEBUG (MainThread) [custom_components.alarmdotcom.binary_sensor] Processing state DeviceState.IDLE for None
2023-01-15 07:50:07.248 DEBUG (MainThread) [custom_components.alarmdotcom.binary_sensor] Processing state DeviceState.DRY for None
2023-01-15 07:50:07.248 DEBUG (MainThread) [custom_components.alarmdotcom.binary_sensor] Processing state DeviceState.DRY for None
2023-01-15 07:50:07.249 DEBUG (MainThread) [custom_components.alarmdotcom.binary_sensor] Processing state DeviceState.CLOSED for None
2023-01-15 07:50:07.250 DEBUG (MainThread) [custom_components.alarmdotcom.binary_sensor] Processing state DeviceState.DRY for None
2023-01-15 07:50:07.251 DEBUG (MainThread) [custom_components.alarmdotcom.binary_sensor] Processing state DeviceState.CLOSED for None
2023-01-15 07:50:07.251 DEBUG (MainThread) [custom_components.alarmdotcom.binary_sensor] Processing state DeviceState.CLOSED for None
2023-01-15 07:50:07.252 DEBUG (MainThread) [custom_components.alarmdotcom.binary_sensor] Processing state DeviceState.CLOSED for None
2023-01-15 07:50:07.252 DEBUG (MainThread) [custom_components.alarmdotcom.binary_sensor] Processing state DeviceState.CLOSED for None
2023-01-15 07:50:07.253 DEBUG (MainThread) [custom_components.alarmdotcom.binary_sensor] Processing state DeviceState.CLOSED for None
2023-01-15 07:50:07.253 DEBUG (MainThread) [custom_components.alarmdotcom.binary_sensor] Processing state DeviceState.CLOSED for None
2023-01-15 07:50:07.253 DEBUG (MainThread) [custom_components.alarmdotcom.binary_sensor] Processing state DeviceState.CLOSED for None
2023-01-15 07:50:07.253 DEBUG (MainThread) [custom_components.alarmdotcom.binary_sensor] Processing state DeviceState.CLOSED for None
2023-01-15 07:50:07.254 DEBUG (MainThread) [custom_components.alarmdotcom.binary_sensor] Processing state DeviceState.CLOSED for None
2023-01-15 07:50:07.254 DEBUG (MainThread) [custom_components.alarmdotcom.binary_sensor] Processing state DeviceState.CLOSED for None
2023-01-15 07:50:07.254 DEBUG (MainThread) [custom_components.alarmdotcom.binary_sensor] Processing state DeviceState.CLOSED for None
2023-01-15 07:50:07.254 DEBUG (MainThread) [custom_components.alarmdotcom.binary_sensor] Processing state DeviceState.CLOSED for None
2023-01-15 07:50:07.255 DEBUG (MainThread) [custom_components.alarmdotcom.binary_sensor] Processing state DeviceState.CLOSED for None
2023-01-15 07:50:07.255 DEBUG (MainThread) [custom_components.alarmdotcom.binary_sensor] Processing state DeviceState.CLOSED for None
2023-01-15 07:50:07.255 DEBUG (MainThread) [custom_components.alarmdotcom.binary_sensor] Processing state DeviceState.CLOSED for None
2023-01-15 07:50:07.255 DEBUG (MainThread) [custom_components.alarmdotcom.binary_sensor] Processing state DeviceState.CLOSED for None
2023-01-15 07:50:07.256 DEBUG (MainThread) [custom_components.alarmdotcom.binary_sensor] Processing state DeviceState.UNKNOWN for None
2023-01-15 07:50:07.256 DEBUG (MainThread) [custom_components.alarmdotcom.binary_sensor] Processing state DeviceState.CLOSED for None
2023-01-15 07:50:07.256 DEBUG (MainThread) [custom_components.alarmdotcom.binary_sensor] Processing state DeviceState.CLOSED for None
2023-01-15 07:50:07.256 DEBUG (MainThread) [custom_components.alarmdotcom.binary_sensor] Processing state DeviceState.CLOSED for None
2023-01-15 07:50:07.256 DEBUG (MainThread) [custom_components.alarmdotcom.binary_sensor] Processing state DeviceState.CLOSED for None
2023-01-15 07:50:07.257 DEBUG (MainThread) [custom_components.alarmdotcom.binary_sensor] Processing state DeviceState.WET for None
2023-01-15 07:50:07.257 DEBUG (MainThread) [custom_components.alarmdotcom.binary_sensor] Processing state DeviceState.CLOSED for None
2023-01-15 07:50:07.258 DEBUG (MainThread) [custom_components.alarmdotcom.binary_sensor] Processing state DeviceState.WET for None
2023-01-15 07:50:07.258 DEBUG (MainThread) [custom_components.alarmdotcom.binary_sensor] Processing state DeviceState.CLOSED for None
2023-01-15 07:50:07.258 DEBUG (MainThread) [custom_components.alarmdotcom.binary_sensor] Processing state DeviceState.CLOSED for None
2023-01-15 07:50:07.258 DEBUG (MainThread) [custom_components.alarmdotcom.binary_sensor] Processing state DeviceState.CLOSED for None
2023-01-15 07:50:07.259 DEBUG (MainThread) [custom_components.alarmdotcom.binary_sensor] Processing state DeviceState.CLOSED for None
2023-01-15 07:50:07.259 DEBUG (MainThread) [custom_components.alarmdotcom.binary_sensor] Processing state DeviceState.CLOSED for None
2023-01-15 07:50:07.259 DEBUG (MainThread) [custom_components.alarmdotcom.binary_sensor] Processing state DeviceState.CLOSED for None
2023-01-15 07:50:07.260 DEBUG (MainThread) [custom_components.alarmdotcom.binary_sensor] Processing state DeviceState.CLOSED for None
2023-01-15 07:50:07.260 DEBUG (MainThread) [custom_components.alarmdotcom.binary_sensor] Processing state DeviceState.CLOSED for None
2023-01-15 07:50:07.260 DEBUG (MainThread) [custom_components.alarmdotcom.binary_sensor] Processing state DeviceState.CLOSED for None
2023-01-15 07:50:07.260 DEBUG (MainThread) [custom_components.alarmdotcom.binary_sensor] Processing state DeviceState.CLOSED for None
2023-01-15 07:50:07.261 DEBUG (MainThread) [custom_components.alarmdotcom.binary_sensor] Processing state DeviceState.CLOSED for None
2023-01-15 07:50:07.261 DEBUG (MainThread) [custom_components.alarmdotcom.binary_sensor] Processing state DeviceState.CLOSED for None
2023-01-15 07:50:07.261 DEBUG (MainThread) [custom_components.alarmdotcom.binary_sensor] Processing state DeviceState.CLOSED for None
2023-01-15 07:50:07.261 DEBUG (MainThread) [custom_components.alarmdotcom.binary_sensor] Processing state DeviceState.CLOSED for None
2023-01-15 07:50:07.282 DEBUG (MainThread) [custom_components.alarmdotcom.alarm_control_panel] Processing state DeviceState.DISARMED for None
2023-01-15 07:50:07.282 DEBUG (MainThread) [custom_components.alarmdotcom.alarm_control_panel] Processing state DeviceState.DISARMED for_

**Comment by thomasshawn** [comment]
Checking in

**Comment by elahd** [comment]
Thanks for the logs. I'll take another look over the weekend.

**Comment by thomasshawn** [comment]
Touching base on this one

**Comment by elahd** [comment]
Alright -- try again by reinstalling from the master branch. I'm flying blind here since my own panel doesn't support night mode. Do you have an Arm (Night) option in ADC? I don't see one in the screenshot you provided.

**Comment by thomasshawn** [comment]
On my end I have an icon labeled sleep and what that does is it sets the alarm but it also toggles the no entry delay so the alarm instantly sets off if someone opens the door it doesn't give you 30 seconds to disarm. And that's what I'm trying to accomplish and that's what I understood night mode to be


 
 
  On Tue, Feb 14, 2023 at 12:14 PM, Elahd ***@***.***> wrote:   


Alright -- try again by reinstalling from the master branch. I'm flying blind here since my own panel doesn't support night mode. Do you have an Arm (Night) option in ADC? I don't see one in the screenshot you provided.

**Comment by thomasshawn** [comment]
If I could just create a scene where the no entry delay is activated then I could call that. How to enable that
 
 
  On Tue, Feb 14, 2023 at 2:10 PM, shawn ***@***.***> wrote:   On my end I have an icon labeled sleep and what that does is it sets the alarm but it also toggles the no entry delay so the alarm instantly sets off if someone opens the door it doesn't give you 30 seconds to disarm. And that's what I'm trying to accomplish and that's what I understood night mode to be


 
 
  On Tue, Feb 14, 2023 at 12:14 PM, Elahd ***@***.***> wrote:   


Alright -- try again by reinstalling from the master branch. I'm flying blind here since my own panel doesn't support night mode. Do you have an Arm (Night) option in ADC? I don't see one in the screenshot you provided.

**Comment by elahd** [comment]
Got it. That isn't considered night arming as far as ADC is concerned. That's just setting a scene called Sleep. Arm Night is a distinct option at the same level as Arm Stay and Arm Away. I can take a look at enabling scenes.

**Comment by thomasshawn** [comment]
I saw there was an update today downloaded it but I don't see any significant changes I still see night as an option. Just making sure I'm not missing something if you're working on the scenes we discussed or the ability to use the entry delay bypass
 
 
  On Tue, Feb 14, 2023 at 2:28 PM, Elahd ***@***.***> wrote:   


Got it. That isn't considered night arming as far as ADC is concerned. That's just setting a scene called Sleep. Arm Night is a distinct option at the same level as Arm Stay and Arm Away. I can take a look at enabling scenes.

**Comment by elahd** [comment]
Working on scenes. The entry delay bypass already works. It's controlled via the Configuration screens for the Alarm.com integration.

Can you post the debug data for your control panel using the instructions at https://github.com/pyalarmdotcom/alarmdotcom/wiki/How-to-Test-&-Debug#get-debug-data-for-a-single-entity?

**Comment by thomasshawn** [comment]
Ok,
I was able to get the "no entry delay" to work.I still don't have access to the "night" option it shows it as an option but when I activate it I get an error. So I'll ignore that.
So, for now, until it/when scenes are an option within the integration I've configured HOME to activate the no entry delay (that will be our new NIGHT mode for now) and AWAY will allow the entry delay for coming in from outside.
Scenes are preferable because they have more descriptive names. But this is a plausible work around and in HA I could make a button that says whatever I want and tie it to the HOME action in HA if it comes to that.
 
 
  On Thu, Feb 23, 2023 at 3:20 PM, Elahd ***@***.***> wrote:   


Working on scenes. The entry delay bypass already works. It's controlled via the Configuration screens for the Alarm.com integration.

Can you post the debug data for your control panel using the instructions at https://github.com/pyalarmdotcom/alarmdotcom/wiki/How-to-Test-&-Debug#get-debug-data-for-a-single-entity?

**Comment by elahd** [comment]
Closing to merge the scenes request into #270.
