### ISSUE TITLE
Error handling request during setup

### ISSUE THREAD

**Issue by vlape** [pyalarmdotcom/alarmdotcom#256]
After prompted for credentials, error generated before promoting for 2FA.
Fresh install of home assistant and Alarm.com app via HACS.
Home Assistant 2023.4.6
Supervisor 2023.04.0
Operating System 10.0
Frontend 20230411.1 - latest
running on Home Assistant Yellow

**Troubleshooting steps:**
Restart HA
Reinstall Alarm.com app
Ran `ha core check`, no errors prodiced.

Reinstall HA & Alarm.com app. Same result.

```
This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/alarmdotcom/alarmhub.py:84
Integration: Alarm.com (documentation, issues)
First occurred: 12:29:35 PM (1 occurrences)
Last logged: 12:29:35 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 146, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 180, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 271, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/alarmdotcom/config_flow.py", line 89, in async_step_user
    login_result = await self._alarmhub.async_login(
  File "/config/custom_components/alarmdotcom/alarmhub.py", line 84, in async_login
    login_result = await self.system.async_login()
  File "/usr/local/lib/python3.10/site-packages/pyalarmdotcomajax/__init__.py", line 223, in async_login
    if not self._two_factor_cookie and await self._async_requires_2fa():
  File "/usr/local/lib/python3.10/site-packages/pyalarmdotcomajax/__init__.py", line 870, in _async_requires_2fa
    self._two_factor_method = OtpType(
  File "/usr/local/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.10/enum.py", line 710, in __new__
    raise ve_exc
ValueError: None is not a valid OtpType

```

**Comment by elahd** [comment]
Tracking in #257.
