### ISSUE TITLE
ETA for next release?

### ISSUE THREAD

**Issue by Nealtron** [pyalarmdotcom/alarmdotcom#262]
I've had to revert from 2.2.2 back to 2.2.1 and eventually 2.2.0 in order to re-stabilize my alarm.com integration. I had seen some discussions back in March that there was a pending refactor looming to hopefully resolve some of those issues. How is that development coming along?

**Comment by elahd** [comment]
Not fast but it is coming along. I hope to have a new release of the underlying pyalarmdotcomajax library within a week to solicit help with testing.

**Comment by Nealtron** [comment]
That's great news. I assumed it was going to be a lengthy process to rebase the code, but was concerned with the dip in insights activity and decided to ask. Thank you!

**Comment by smshapiro85** [comment]
Thank you Elahd!

**Comment by elahd** [comment]
@Nealtron @smshapiro85 

I've released an update to the underlying pyalarmdotcomajax library that powers this HA integration. This release fixes issues with 2FA, introduces a new method for refreshing device data, and supports real time notifications. See https://github.com/pyalarmdotcom/alarmdotcom/discussions/265 for testing details. Thanks!

**Comment by elahd** [comment]
I just released v3.0.0-beta of the integration with support for real time "push" updates and a fix for 2FA. 

If you don't see this version, go to HACS, click on integrations, click on Alarm.com, click on the 3 dot menu at the top right of the screen, click on redownload, and turn "show beta versions". v3 will appear shortly after turning this setting on.

**Comment by smshapiro85** [comment]
Thank you @elahd 
I deleted the integration and reinstalled, then reauthenticated without issue, however I am seeing the following two issues in the logs:

```

This error originated from a custom integration.

Logger: custom_components.alarmdotcom.controller
Source: custom_components/alarmdotcom/controller.py:106 
Integration: Alarm.com (documentation, issues) 
First occurred: 2:50:13 PM (54 occurrences) 
Last logged: 8:09:50 PM

Unexpected error fetching Toll Brothers Smart Home Technologies, Inc.:scrubbed@gmail.com data:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pyalarmdotcomajax/__init__.py", line 784, in _async_get_system
    async with self._websession.get(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 643, in _request
    resp.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1005, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('https://www.alarm.com/web/api/systems/systems/13592182')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 217, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/alarmdotcom/controller.py", line 106, in async_update
    await self.api.async_update()
  File "/usr/local/lib/python3.10/site-packages/pyalarmdotcomajax/__init__.py", line 225, in async_update
    raw_devices: list[dict] = await self._async_get_system(self._active_system_id)
  File "/usr/local/lib/python3.10/site-packages/pyalarmdotcomajax/__init__.py", line 800, in _async_get_system
    raise DataFetchFailed from err
pyalarmdotcomajax.errors.DataFetchFailed

``` 

and

```
This error originated from a custom integration.

Logger: pyalarmdotcomajax
Source: custom_components/alarmdotcom/controller.py:106 
Integration: Alarm.com 
First occurred: 2:50:13 PM (54 occurrences) 
Last logged: 8:09:50 PM

Failed to get system devices.

```

**Comment by elahd** [comment]
@smshapiro85 Try v3.0.0-beta.2.

**Comment by smshapiro85** [comment]
@elahd updated to beta 2 and errors are no longer appearing, however upon arming/disarming, the "Code" is asked for every time, even though the code as been added to the config. I also tried clearing out the pin using the "CLEAR!" feature, and then readding the pin, but it is still being asked for.
![image](https://github.com/pyalarmdotcom/alarmdotcom/assets/41717535/8fbfa22e-aa68-4db6-894c-98adf47ac91c)

**Comment by smshapiro85** [comment]
Running the beta 2 integration for 24 hours and zero issues in the logs! Just experiencing the issue when arming, it asks for the code every time.

**Comment by pdobrien3** [comment]
I ended up rolling back to 2.2.0. I was getting some arm/disarm notifications that were not matching up and I tried to arm through hass today and it wouldn’t do it. Was working strong for about 24 hours and then things seemed off. I may try again in a few days. Curious if anyone else seeing similar issues after a day or so though.

**Comment by elahd** [comment]
Can you try again with v3.0.1? If that doesn't work, specifically for @smshapiro85, can you provide logs using the instructions I posted at https://github.com/pyalarmdotcom/alarmdotcom/issues/279#issuecomment-1566205051?

**Comment by Nealtron** [comment]
I can't get 3.0.1 to work at all. After installing the update and reloading Home Assistant, Home Assistant notified me that I needed to modify my configuration, at which point it prompted me for my Alarm.com credentials. I entered the credentials, and it kicked back with "Unknown error occurred" though I received a successful login notification from the Alarm.com app. 

After retrying my credentials several times, I completely removed the existing integration, rebooted Home Assistant again, and tried to add the integration from scratch, but received the same "Unknown error occurred" message, but once again received a "Successful Web Login" from the Alarm.com app.

The account I'm using for the integration is a read-only user, and MFA is not enabled. 

All logs appear the be the same as the following:
```
This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/alarmdotcom/config_flow.py:177
Integration: Alarm.com (documentation, issues)
First occurred: 8:17:44 AM (3 occurrences)
Last logged: 9:25:44 AM

Error handling request
Traceback (most recent call last):
  File "/config/custom_components/alarmdotcom/config_flow.py", line 96, in async_step_user
    await self._controller.initialize_lite(
  File "/config/custom_components/alarmdotcom/controller.py", line 114, in initialize_lite
    await self.api.async_login()
  File "/usr/local/lib/python3.10/site-packages/pyalarmdotcomajax/__init__.py", line 590, in async_login
    raise OtpRequired(enabled_2fa_methods)
pyalarmdotcomajax.exceptions.OtpRequired

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 146, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 180, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 271, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/alarmdotcom/config_flow.py", line 105, in async_step_user
    return await self.async_step_otp_select_method()
  File "/config/custom_components/alarmdotcom/config_flow.py", line 177, in async_step_otp_select_method
    vol.Required(CONF_OTP_METHOD, default=self._enabled_otp_methods[0].name): SelectSelector(
IndexError: list index out of range
```
`

**Comment by elahd** [comment]
Try v3.0.3.

**Comment by pdobrien3** [comment]
i rolled back to 2.2.0 because i was out of town for several days  when i came back, i disarmed through the adc app.  took close to a minute for hass to update the state.  i am guessing this is because of dependency upgrades?  i can play with beta releases all day as long as i can roll back to a stable system

**Comment by elahd** [comment]
Test out v3.0.4-beta.1.

**Comment by elahd** [comment]
I'm closing this ticket to consolidate threads. Let's move this over to #288.
