### ISSUE TITLE
Unable to Configure/Login above version 2.2.2

### ISSUE THREAD

**Issue by jprasm** [pyalarmdotcom/alarmdotcom#284]
The integration works for me with versions up to 2.2.2. I am able to login to alarm.com's website without issue. I **do **not**** have 2-FA authentication enabled. 

With version 3+ the integration asks reconfigured, and when I enter my login credentials I get "unknown error".

```
Logger: homeassistant.config_entries
Source: config_entries.py:411
First occurred: 07:43:43 (1 occurrences)
Last logged: 07:43:43

Config entry 'XXXXXXX' for alarmdotcom integration could not authenticate: Authentication failed. Please try logging in again.
```

And:

```
This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/alarmdotcom/config_flow.py:177
Integration: Alarm.com (documentation, issues)
First occurred: 07:45:52 (1 occurrences)
Last logged: 07:45:52

Error handling request
Traceback (most recent call last):
  File "/config/custom_components/alarmdotcom/config_flow.py", line 96, in async_step_user
    await self._controller.initialize_lite(
  File "/config/custom_components/alarmdotcom/controller.py", line 114, in initialize_lite
    await self.api.async_login()
  File "/usr/local/lib/python3.10/site-packages/pyalarmdotcomajax/__init__.py", line 590, in async_login
    raise OtpRequired(enabled_2fa_methods)
pyalarmdotcomajax.exceptions.OtpRequired

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 146, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 180, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 271, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/alarmdotcom/config_flow.py", line 105, in async_step_user
    return await self.async_step_otp_select_method()
  File "/config/custom_components/alarmdotcom/config_flow.py", line 177, in async_step_otp_select_method
    vol.Required(CONF_OTP_METHOD, default=self._enabled_otp_methods[0].name): SelectSelector(
IndexError: list index out of range
```

**Comment by mjakeseaton** [comment]
Weirdly, I fixed this by adding 2FA to my account 🤷‍♂️

**Comment by jprasm** [comment]
Holy hell, adding 2FA to my account worked too. Thank you very much!
I have a skybell doorbell that's attached to my system...but this isn't getting picked up (no entity is created). If you know how to figure that out, let me know!

**Comment by ghds514** [comment]
Also had to downgrade to resolve the same issue. I will try the 2FA technique made popular by @mjakeseaton

**Comment by elahd** [comment]
Sorry about that. It looks like Alarm.com rolled out changes to 2FA for just a subset of Alarm.com providers. My provider no longer lets you disable 2FA -- I thought that this applied to everyone. You should be able to login with 2FA now.

@jprasm Can you [enable debugging](https://github.com/pyalarmdotcom/alarmdotcom/wiki/How-to-Test-&-Debug#enable-code-debugging) to try to capture update failures?

**Comment by jprasm** [comment]
elhad, the 2FA works now - the integration logs in, etc. (it worked once I enabled 2FA with my provider, Bell Canada. Thank you.

I had a secondary problem with v3.xx (no state changes detected by Home Assistant) but after a couple of reboots, it seems to be working. I will report back if it causes problems again. I am using v3.0.2 successfully right now.

**Comment by jprasm** [comment]
Downgrading to 2.2.2. Polling/state changes seem to stop working for me in v3.0.2. I apologize for mixing two separate issues in this thread.

**Comment by jprasm** [comment]
I don't believe I'm getting any errors at all. Just nothing. I disarm or arm the alarm (which works, the alarm panel itself arms and disarms properly) but HA does not register a state change. 

HA does register a state change after a reboot. Then it seems to stop working after a while (but the system actually does arm and disarm).

**Comment by elahd** [comment]
Try v3.0.3.
