### ISSUE TITLE
No attribute _friendly_name_internal

### ISSUE THREAD

**Issue by spaulson500** [pyalarmdotcom/alarmdotcom#308]
**Describe the bug**
Error when trying to lock or unlock doors

**To Reproduce**
activate any lock entity
  - entity: lock.front_door_lock
    type: custom:mushroom-lock-card
  - entity: lock.back_door_lock
    type: custom:mushroom-lock-card
  - entity: lock.garage_door
    type: custom:mushroom-lock-card

**Expected behavior**
Door should lock or unlock

**Home Assistant Version:**
Home Assistant 2023.3.4
Frontend 20230309.0 - latest

**Additional context**
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/alarmdotcom/base_device.py:105
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 9:45:58 AM (38 occurrences)
Last logged: 9:01:25 PM

[139981931163280] 'AttributeBinarySensor' object has no attribute '_friendly_name_internal'
[139981931163280] Error handling message: Unknown error (unknown_error) xxxxxxxxxx from 172.17.0.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36)
[139981728215776] 'AttributeBinarySensor' object has no attribute '_friendly_name_internal'
[139981933033024] 'AttributeBinarySensor' object has no attribute '_friendly_name_internal'
[139981933033024] Error handling message: Unknown error (unknown_error) xxxxxxxxxx from 172.17.0.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.58)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1808, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1845, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 686, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 961, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 726, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/lock/__init__.py", line 106, in _async_unlock
    await entity.async_unlock(**remove_entity_service_fields(service_call))
  File "/config/custom_components/alarmdotcom/lock.py", line 144, in async_unlock
    await self._device.async_unlock()
  File "/usr/local/lib/python3.10/site-packages/pyalarmdotcomajax/devices/lock.py", line 45, in async_unlock
    await self.async_handle_external_desired_state_change(self.DeviceState.UNLOCKED)
  File "/usr/local/lib/python3.10/site-packages/pyalarmdotcomajax/devices/__init__.py", line 297, in async_handle_external_desired_state_change
    await self.async_handle_external_attribute_change(
  File "/usr/local/lib/python3.10/site-packages/pyalarmdotcomajax/devices/__init__.py", line 319, in async_handle_external_attribute_change
    external_callback()
  File "/config/custom_components/alarmdotcom/base_device.py", line 105, in _update_device_data
    f"Updated {self.device_type_name} {self._friendly_name_internal()} ({self._adc_id}): {self.state}"
AttributeError: 'AttributeBinarySensor' object has no attribute '_friendly_name_internal'

Further information
2023-06-27 02:17:00.644 ERROR (MainThread) [homeassistant.components.lock] Error adding entities for domain lock with platform alarmdotcom
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 442, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 717, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 806, in add_to_platform_finish
await self.async_added_to_hass()
File "/config/custom_components/alarmdotcom/base_device.py", line 73, in async_added_to_hass
self._update_device_data()

**Comment by spaulson500** [comment]
problem solved with upgrade to latest version on 7/18/23
