### ISSUE TITLE
KeyError: 34303135 - error log

### ISSUE THREAD

**Issue by impreza2k3** [pyalarmdotcom/alarmdotcom#343]
Errors showing up in log that appear to be related to an unknown device

ADC output shows 34303135 to be "Home" under the Scene section

====[ Scene ]====

Away (34303136)
ATTRIBUTES: [DISARMS_ALARM: False] 
**Home (34303135)**
ATTRIBUTES: [DISARMS_ALARM: True] 
Sleep (34303137)
ATTRIBUTES: [DISARMS_ALARM: False] 
Wake Up (34303138)
ATTRIBUTES: [DISARMS_ALARM: True] 

KeyError: 34303135

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 233, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 389, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 172, in async_update_listeners
    update_callback()
  File "/config/custom_components/alarmdotcom/base_device.py", line 91, in _handle_coordinator_update
    super()._handle_coordinator_update()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 469, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 779, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 879, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 823, in _async_generate_attributes
    attr.update(self.extra_state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alarmdotcom/base_device.py", line 198, in extra_state_attributes
    raw = self._controller.api.devices.get(self._adc_id).raw_attributes
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyalarmdotcomajax/devices/registry.py", line 301, in get
    raise UnkonwnDevice(device_id) from err
pyalarmdotcomajax.exceptions.UnkonwnDevice: Unknown device ID '34303135'.
2023-11-01 10:17:36.725 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pyalarmdotcomajax/devices/registry.py", line 299, in get
    return self._devices[device_id]
           ~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 34303135

**To Reproduce**
Steps to reproduce the behavior:

Reboot home assistant

**Expected behavior**
Not sure why this is showing in the log now.


**Home Assistant Version:**
Home Assistant 2023.10.5 
Frontend 20231005.0 - latest 


**Additional context**
Add any other context about the problem here.

**Comment by elahd** [comment]
This is fixed in v3.0.12.
