### ISSUE TITLE
Unexpected WebSocket error

### ISSUE THREAD

**Issue by smshapiro85** [pyalarmdotcom/alarmdotcom#395]
**Describe the bug**
Within the last week or two (unsure if this is a result of updating to 2024.4.0) I have begun seeing Unexpected WebSocket errors in the logs. I have not made any changes to the config.

On latest version- 3.0.13

**To Reproduce**
N/A - Logging error

**Screenshots**
See logs below and config:
![image](https://github.com/pyalarmdotcom/alarmdotcom/assets/41717535/50b30199-fa58-44b5-967e-d535d1fdc385)

**Home Assistant Version:**
2024.4.0

**Additional context**
Log message

Logger: pyalarmdotcomajax.websockets.client
Source: /usr/local/lib/python3.12/site-packages/pyalarmdotcomajax/websockets/client.py:150
First occurred: April 6, 2024 at 10:35:19 AM (39 occurrences)
Last logged: 10:26:40 AM

Unexpected WebSocket error
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/pyalarmdotcomajax/websockets/client.py", line 114, in _connect
    async with self._websession.ws_connect(
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 1194, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 832, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 605, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 966, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/streams.py", line 622, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno 104] Connection reset by peer

**Comment by smshapiro85** [comment]
Closing this issue. Suddenly, it has not reoccurred.
