### ISSUE TITLE
Unexpected Websocket Error

### ISSUE THREAD

**Issue by azoner2965** [pyalarmdotcom/alarmdotcom#406]
For the past month or so I have been receiving the following error in my logs, 71 of them in the last 12 hours:

It has persisted through the last few core updates. An uninstall/reinstall of alarmdotcom does not help. 

Logger: pyalarmdotcomajax.websockets.client
Source: /usr/local/lib/python3.12/site-packages/pyalarmdotcomajax/websockets/client.py:150
First occurred: 7:33:59 AM (71 occurrences)
Last logged: 7:20:03 PM

Unexpected WebSocket error
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 978, in _read_ready__get_buffer
    nbytes = self._sock.recv_into(buf)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/pyalarmdotcomajax/websockets/client.py", line 114, in _connect
    async with self._websession.ws_connect(
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 1197, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 835, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 608, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 976, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/streams.py", line 640, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno 104] Connection reset by peer

**Comment by azoner2965** [comment]
This issue eventually went away.
