### ISSUE TITLE
Authentication now "needs attention" (despite working fine)

### ISSUE THREAD

**Issue by lutzky** [pyalarmdotcom/alarmdotcom#419]
**Describe the bug**

Note: Recently Gokonnect's alarm.com started requiring two-factor authentication - the flow seems to work fine. However, I think I now have an issue - I'm not sure that these started at the same time.

![image](https://github.com/user-attachments/assets/7e0dd92d-4d89-4135-a69c-82645465e41c)

Despite this error message, the integration appears to work fine. Occasionally - I'm not sure when and how - a login prompt will appear in the HASS UI. If I follow through with it, the above screen shows another entry under "Hubs", with 0 devices and 0 entities. 

I don't know how to reproduce this.

**Home Assistant Version:** 2024.10.0

Possibly relevant log entries:

Logger: homeassistant.components.button
Source: helpers/entity_platform.py:761
integration: Button (documentation, issues)
First occurred: 6:18:22 PM (14 occurrences)
Last logged: 6:18:22 PM

Platform alarmdotcom does not generate unique IDs. ID REDACTED-11_debug already exists - ignoring button.master_bedroom_middle_floor_glassbreak_debug
Platform alarmdotcom does not generate unique IDs. ID REDACTED-6_debug already exists - ignoring button.patio_door_debug
Platform alarmdotcom does not generate unique IDs. ID REDACTED-13_debug already exists - ignoring button.back_room_debug
Platform alarmdotcom does not generate unique IDs. ID REDACTED-9_debug already exists - ignoring button.siren_9_debug
Platform alarmdotcom does not generate unique IDs. ID REDACTED-4_debug already exists - ignoring button.upstairs_landing_debug

Logger: homeassistant.config_entries
Source: config_entries.py:622
First occurred: 6:16:55 PM (1 occurrences)
Last logged: 6:16:55 PM

Config entry 'GoKonnect Smart Home Security:lutzky@gmail.com' for alarmdotcom integration could not authenticate: Authentication failed. Please try logging in again.

**Comment by hayden567** [comment]
I see this issue as well. It seemed to start happening after I was forced to enable 2FA.

**Comment by nitroxjunkie** [comment]
I'm another one seeing this issue - same as above; after enabling (required) MFA, I am seeing the same "authentication failed" message, and I am also seeing a second entry with no devices as well as my original entry with my alarm sensors and contacts.

**Comment by Raul-7-7** [comment]
Same issue here.

**Comment by glen4cindy** [comment]
I'm also having the same issue. It also started for me after I enabled 2FA. 
It seems that in my case I can authenticate and alarm.com will work for hours to a few days but this error always returns.

**Comment by elahd** [comment]
Closing. Please reopen if the issue persists in [v4](https://github.com/pyalarmdotcom/alarmdotcom/releases/tag/v4.0.0-beta.1).

**Comment by lutzky** [comment]
I do not have permission to reopen the issue, but it persists in v4 (specifically v4.0.0-beta2)

**Comment by lutzky** [comment]
This persists in 4.0.1-beta.2. Here are some debug logs:

```
2025-05-31 21:29:47.093 WARNING (MainThread) [homeassistant.config_entries] Config entry 'GoKonnect Smart Home Security:lutzky@gmail.com' for alarmdotcom integration could not authenticate
2025-05-31 21:29:48.669 ERROR (MainThread) [homeassistant.components.alarm_control_panel] Platform alarmdotcom does not generate unique IDs. ID 96747708-127 already exists - ignoring alarm_control_panel.panel
2025-05-31 21:29:48.683 ERROR (MainThread) [homeassistant.components.binary_sensor] Platform alarmdotcom does not generate unique IDs. ID 96747708-14 already exists - ignoring binary_sensor.glassbreak_14

...many many more of the above...

2025-05-31 21:31:05.706 ERROR (MainThread) [custom_components.alarmdotcom.config_flow] custom_components.alarmdotcom.config_flow: Incorrect OTP code entered.
Traceback (most recent call last):
  File "/config/custom_components/alarmdotcom/config_flow.py", line 222, in async_step_otp_submit
    mfa_cookie = await self.bridge.auth_controller.submit_otp(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/pyalarmdotcomajax/controllers/auth.py", line 386, in submit_otp
    await self._bridge.post(
    ...<5 lines>...
    )
  File "/usr/local/lib/python3.13/site-packages/pyalarmdotcomajax/__init__.py", line 984, in post
    return await self.request(
           ^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/pyalarmdotcomajax/__init__.py", line 814, in request
    raise AuthenticationFailed(
    ...<2 lines>...
    )
pyalarmdotcomajax.exceptions.AuthenticationFailed
2025-05-31 21:31:11.808 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'alarmdotcom' creates a new entry in a 'reauth' flow, when it is expected to update an existing entry and abort. This will stop working in Home Assistant 2025.11, please create a bug report at https://github.com/pyalarmdotcom/alarmdotcom/issues
2025-05-31 21:31:14.591 ERROR (MainThread) [homeassistant.components.alarm_control_panel] Platform alarmdotcom does not generate unique IDs. ID 96747708-127 already exists - ignoring alarm_control_panel.panel

...many more of the above...

2025-05-31 21:31:51.852 WARNING (MainThread) [homeassistant.config_entries] Config entry 'GoKonnect Smart Home Security:lutzky@gmail.com' for alarmdotcom integration could not authenticate
2025-05-31 21:32:26.847 ERROR (MainThread) [homeassistant.components.alarm_control_panel] Platform alarmdotcom does not generate unique IDs. ID 96747708-127 already exists - ignoring alarm_control_panel.panel

...many more of the above...

2025-05-31 21:32:42.716 INFO (MainThread) [custom_components.alarmdotcom] custom_components.alarmdotcom: Initializing Alarmdotcom from config entry.
2025-05-31 21:32:42.716 INFO (MainThread) [custom_components.alarmdotcom] 
===================================================================
alarmdotcom
This is a custom component
If you have any issues with this you need to open an issue here:
https://github.com/pyalarmdotcom/alarmdotcom/issues
===================================================================

2025-05-31 21:32:44.443 ERROR (MainThread) [homeassistant] Error doing job: Unclosed client session (None)
2025-05-31 21:32:44.443 ERROR (MainThread) [homeassistant] Error doing job: Unclosed client session (None)
2025-05-31 21:32:44.723 WARNING (MainThread) [homeassistant.config_entries] Config entry 'GoKonnect Smart Home Security:lutzky@gmail.com' for alarmdotcom integration could not authenticate
2025-05-31 21:32:44.724 DEBUG (MainThread) [custom_components.alarmdotcom.config_flow] Reauthenticating.
```

**Comment by lutzky** [comment]
This is odd - I seem to have worked around this. I'm back on 3.0.14, and the integration had completely stopped working for some reason. I noticed that I had ~8 different Hubs configured; I removed all of them and created a new one. The issue, which was 100% consistent earlier, now no longer reproduces - restarting homeassistant, reloading the integration - everything now works fine. I have no idea why I had multiple duplicate hubs; my best bet is that turning on 2FA made enough of a difference in config that a duplicate hub was created.

That being said, https://github.com/pyalarmdotcom/alarmdotcom/issues/419#issuecomment-2738784561 said that this takes several days to reproduce, so I'll keep my eye on it. In the meantime, other folks who are having this problem - please  check whether you have multiple hubs (in `/config/integrations/integration/alarmdotcom`), and if so - perhaps removing them all and creating a new one would help. (Careful, this might unlink any dashboards or automations you have set up, as the new name might not match; you'll also have to reconfigure the rooms for all of the devices).
