### ISSUE TITLE
Issue on Authentication (or setup) AttributeError: 'list' object has no attribute 'get'

### ISSUE THREAD

**Issue by FedgarLurch** [pyalarmdotcom/alarmdotcom#424]
Please provide as much detail as possible. It's helpful to include Home Assistant debug logs from this integration. Instructions for enabling debugging are available at https://github.com/pyalarmdotcom/alarmdotcom/wiki/How-to-Test-&-Debug#enable-code-debugging. (Alarmdotcom debug logs are verbose, so don't forget to disable debug logging when you're done!)

**Describe the bug**
Whenever I try to log I get the following error on 3.0.13.
```
2024-11-25 09:29:14.513 ERROR (MainThread) [custom_components.alarmdotcom.controller] Unexpected error fetching AAA Smart Business Security:[REDACTED] data
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
self.data = await self._async_update_data()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 271, in _async_update_data
return await self.update_method()
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/alarmdotcom/controller.py", line 164, in async_update
await self.api.async_update()
File "/usr/local/lib/python3.12/site-packages/pyalarmdotcomajax/__init__.py", line 235, in async_update
has_image_sensors = await self._async_device_type_present(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/pyalarmdotcomajax/__init__.py", line 1019, in _async_device_type_present
return len(json_rsp["data"].get("relationships", {}).get(device_type_id, {}).get("data", [])) > 0
^^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'get'
```

Now, I had previously had this issue, but I was able to downgrade my setup to 2.2.3 which works enough, with the only issue being that I run into the states not refreshing after some amount of time. I am planning on systematically going through the versions and upgrading until it stops working.

**To Reproduce**
Setup the integration
Login
Behold the errors! lol

**Home Assistant Version:**
I have tried this on multiple versions of HA, I am currently running 
2024.9.1 & 13.1 but I am going through and upgrading and if I find anything, I will report back.

**Additional context**

I always hate leaving bug reports because I feel like if I just troubleshot a bit more, id get it figured out. So please point me in a direction if I was close! Thanks!

**Comment by elahd** [comment]
Closing. Please reopen if the issue persists in [v4](https://github.com/pyalarmdotcom/alarmdotcom/releases/tag/v4.0.0-beta.1).
